#!/bin/bash
echo $$ > /var/run/myscript.pid

sigterm_handler() {
    echo "I hate the kill command"
    rm -f /var/run/myscript.pid
    exit 0
}

sigquit_handler() {
    rm -f /var/run/myscript.pid
    exit 0
}

trap 'echo "Y U no love me?!"' SIGINT
trap sigterm_handler SIGTERM
trap sigquit_handler SIGQUIT

while true; do
    echo "To infinity and beyond"
    sleep 2
done
