#!/bin/bash
echo $$ > /var/run/myscript.pid

cleanup_and_exit() {
    rm -f /var/run/myscript.pid
    exit 0
}

sigterm_handler() {
    echo "I hate the kill command"
    rm -f /var/run/myscript.pid
    exit 0
}

trap 'echo "Y U no love me?!"' SIGINT
trap sigterm_handler SIGTERM
trap cleanup_and_exit SIGQUIT

while true; do
    echo "To infinity and beyond"
    sleep 2
done
